name: CI Build

on: 
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  InstallBoost:
    name: install boost in linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Vcpkg Search Boost
        run: |
          sudo -E vcpkg search boost 
          sudo -E vcpkg install boost
          sudo -E vcpkg export boost --7zip
          du -sh /opt/vcpkg/vcpkg-export-*.7z
          cd /opt/vcpkg/installed/x64-linux/lib
          ls -al
          du -sh

          
